services:
  royal-gap-production:
    image: royal-gap-production
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
      args:
        - STAGE=prod
    restart: always
    networks:
      - royal-gap-network
      - royal-gap-network-prod
    environment:
      - HOST_DB_CONTAINER=royal-gap-production-db
      - URL_SERVER_CONTAINER=https://gapv2.ngrok.app
    command: ["${USER_DB}", "${PASS_DB}"]
    depends_on:
      - royal-gap-production-db

  royal-gap-production-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: gapv3
      MYSQL_USER: ${USER_DB}
      MYSQL_PASSWORD: ${PASS_DB}
      MYSQL_ROOT_PASSWORD: ${PASS_DB}
    networks:
      - royal-gap-network-prod
    volumes:
      - royal-gap-production-volume-db:/var/lib/mysql

  royal-gap-production-phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: royal-gap-production-db
      PMA_USER: ${USER_DB}
      PMA_PASSWORD: ${PASS_DB}
    networks:
      - royal-gap-network-prod
    ports:
      - 8335:80
    depends_on:
      - royal-gap-production-db

networks:
  royal-gap-network:
  royal-gap-network-prod:

volumes:
  royal-gap-production-volume-db:
