services:
  reverse-proxy-gap:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/royal-gap.conf:ro
    ports:
      - 3010:443
    networks:
      - royal-gap-network

networks:
  royal-gap-network: