server {
    listen 443;

    location / {
        proxy_pass http://royal-gap-production:8080;
    }

    location /socket.io/ {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;

        proxy_pass http://royal-gap-production:8080;
    }

    location /uat/ {
        rewrite ^/uat/(.*)$ /$1 break;
        proxy_pass http://royal-gap-uat:8080/;
    }

    location /uat/socket.io/ {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;

        proxy_pass http://royal-gap-uat:8080/socket.io/;
    }
}